version: '3'
services:
  db:
    image: dm8:dm8_20240613_rev229704_x86_rh6_64
    container_name: dameng
    restart: always
    privileged: true
    volumes:
      - './db/data:/opt/dmdbms/data'
    ports:
      - '5236:5236'
    environment:
      - CASE_SENSITIVE=0
      - UNICODE_FLAG=1
      - INSTANCE_NAME=dmdb
      - SYSDBA_PWD=cssauxpajy
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    privileged: true
    ports:
      - '3306:3306'
    volumes:
      - './db/mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=cssauxpajy
