server:
  port: 8088

spring:
  freemarker:
    suffix: .ftl
    check-template-location: true
  datasource:
    multiple:
      primary: dameng
      configs:
        dameng:
          driver-class-name: dm.jdbc.driver.DmDriver
          url: jdbc:dm://localhost:5236?schema=dbo
          username: SYSDBA
          password: cssauxpajy
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/testdb
          username: root
          password: cssauxpajy


mybatis-plus:
  type-aliases-package: com.zn.kcms
