server:
  port: 8088

spring:
  freemarker:
    suffix: .ftl
    check-template-location: true
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236
    username: SYSDBA
    password: cssauxpajy

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zn.kcms
  global-config:
    db-config:
      schema: dbo
